[package]
name = "conjure_oxide"
version = "0.0.1"
edition = "2021"
default-run = "conjure_oxide"

# these are available inside build.rs
[build-dependencies]
walkdir = "2.5.0"

[dependencies]
conjure_core = { path = "../crates/conjure_core" }

uniplate = "0.1.2"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
serde_with = "3.11.0"
thiserror = "1.0.67"
anyhow = "1.0.92"
clap = { version = "4.5.20", features = ["derive"] }
strum_macros = "0.26.4"
strum = "0.26.3"
versions = "6.3.0"
linkme = "0.3.29"
walkdir = "2.5.0"
regex = "1.11.1"
log = "0.4.22"
structured-logger = "1.0.3"
schemars = "0.8.21"
toml = "0.8.19"
glob = "0.3.1"
rand = "0.8.5"
rustsat = "0.6.1"
rustsat-minisat = "0.4.1"

[features]

unstable = []
unstable-solver-interface = ["unstable"]

[lints]
workspace = true

[dev-dependencies]
pretty_assertions = "1.4.1"
